### ISSUE TITLE
有没有二进制的安装方法。

### ISSUE THREAD

**Issue by ggaaooppeenngg** [QcloudApi/qcloudcli#4]
我的环境不能装 pip，能不能提供二进制的安装方法。

**Comment by QcloudApi** [comment]
是因为什么原因不能安装pip呢？
您的环境具体是什么呢？windows，linux，mac？32位，64位？
qcloudcli需要走公网https访问*.api.qcloud.com，如果是因为在内网的缘故导致不能装pip，那么也一样无法使用qcloudcli的。

**Comment by ggaaooppeenngg** [comment]
是在 docker 里面基于 debian 的 base 打的，发现不能用 apt-get install pip，我换成二进制安装 pip 就好了。

**Comment by QcloudApi** [comment]
这个issue可以关闭了吗？
